# Generated by Django 4.1.4 on 2022-12-07 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='weblog/images/')),
                ('title_proj', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('tags', models.CharField(max_length=50)),
                ('url_git', models.URLField(blank=True)),
                ('date', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
    ]
